apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mysql-test
  name: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql-test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql-test
    spec:
      containers:
      - image: mysql
        name: mysql
        ports:
        - containerPort: 80