apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: test
    release: stabel
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080