apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  type: NodePort
  selector:
    app: test
    release: stabel
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080